[package]
name = "virtexp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steel-core = { git = "https://github.com/mattwparas/steel.git" }
virt = "0.3.1"
